openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    This is documentation of contacts app

servers:
  - url: 127.0.0.1:3000
#  - url: #посилання на задеплоєний сайт
tags:
  - name: Contacts
    description: Operation with contacts
paths:
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{contactId}/get.yaml  
    patch: 
      $ref: ../swagger/paths/contacts/{contactId}/patch.yaml 
    delete: 
      $ref: ../swagger/paths/contacts/{contactId}/delete.yaml     
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
